//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitsmlStoreServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.witsml.org/wsdl/120", ConfigurationName="WitsmlStoreServiceReference.IWitsmlStore")]
    public interface IWitsmlStore
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_AddToStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_AddToStoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_AddToStoreResponse WMLS_AddToStore(WitsmlStoreServiceReference.WMLS_AddToStoreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_AddToStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_AddToStoreResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_AddToStoreResponse> WMLS_AddToStoreAsync(WitsmlStoreServiceReference.WMLS_AddToStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_DeleteFromStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_DeleteFromStoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_DeleteFromStoreResponse WMLS_DeleteFromStore(WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_DeleteFromStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_DeleteFromStoreResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_DeleteFromStoreResponse> WMLS_DeleteFromStoreAsync(WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.witsml.org/message/120) of message WMLS_GetBaseMsgRequest does not match the default value (http://www.witsml.org/wsdl/120)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetBaseMsg", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetBaseMsgResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse WMLS_GetBaseMsg(WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetBaseMsg", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetBaseMsgResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse> WMLS_GetBaseMsgAsync(WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetCap", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetCapResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_GetCapResponse WMLS_GetCap(WitsmlStoreServiceReference.WMLS_GetCapRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetCap", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetCapResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetCapResponse> WMLS_GetCapAsync(WitsmlStoreServiceReference.WMLS_GetCapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetFromStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetFromStoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_GetFromStoreResponse WMLS_GetFromStore(WitsmlStoreServiceReference.WMLS_GetFromStoreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetFromStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetFromStoreResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetFromStoreResponse> WMLS_GetFromStoreAsync(WitsmlStoreServiceReference.WMLS_GetFromStoreRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.witsml.org/message/120) of message WMLS_GetVersionRequest does not match the default value (http://www.witsml.org/wsdl/120)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetVersion", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_GetVersionResponse WMLS_GetVersion(WitsmlStoreServiceReference.WMLS_GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetVersion", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_GetVersionResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetVersionResponse> WMLS_GetVersionAsync(WitsmlStoreServiceReference.WMLS_GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_UpdateInStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_UpdateInStoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WitsmlStoreServiceReference.WMLS_UpdateInStoreResponse WMLS_UpdateInStore(WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_UpdateInStore", ReplyAction="http://www.witsml.org/wsdl/120/IWitsmlStore/WMLS_UpdateInStoreResponse")]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_UpdateInStoreResponse> WMLS_UpdateInStoreAsync(WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_AddToStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_AddToStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_AddToStoreRequest()
        {
        }
        
        public WMLS_AddToStoreRequest(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.XMLin = XMLin;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_AddToStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_AddToStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_AddToStoreResponse()
        {
        }
        
        public WMLS_AddToStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_DeleteFromStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_DeleteFromStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_DeleteFromStoreRequest()
        {
        }
        
        public WMLS_DeleteFromStoreRequest(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.QueryIn = QueryIn;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_DeleteFromStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_DeleteFromStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_DeleteFromStoreResponse()
        {
        }
        
        public WMLS_DeleteFromStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetBaseMsg", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetBaseMsgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short ReturnValueIn;
        
        public WMLS_GetBaseMsgRequest()
        {
        }
        
        public WMLS_GetBaseMsgRequest(short ReturnValueIn)
        {
            this.ReturnValueIn = ReturnValueIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetBaseMsgResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetBaseMsgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLS_GetBaseMsgResponse()
        {
        }
        
        public WMLS_GetBaseMsgResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetCap", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetCapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OptionsIn;
        
        public WMLS_GetCapRequest()
        {
        }
        
        public WMLS_GetCapRequest(string OptionsIn)
        {
            this.OptionsIn = OptionsIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetCapResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetCapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CapabilitiesOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLS_GetCapResponse()
        {
        }
        
        public WMLS_GetCapResponse(short Result, string CapabilitiesOut, string SuppMsgOut)
        {
            this.Result = Result;
            this.CapabilitiesOut = CapabilitiesOut;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetFromStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetFromStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_GetFromStoreRequest()
        {
        }
        
        public WMLS_GetFromStoreRequest(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.QueryIn = QueryIn;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetFromStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetFromStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLS_GetFromStoreResponse()
        {
        }
        
        public WMLS_GetFromStoreResponse(short Result, string XMLout, string SuppMsgOut)
        {
            this.Result = Result;
            this.XMLout = XMLout;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetVersion", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetVersionRequest
    {
        
        public WMLS_GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetVersionResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLS_GetVersionResponse()
        {
        }
        
        public WMLS_GetVersionResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_UpdateInStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_UpdateInStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_UpdateInStoreRequest()
        {
        }
        
        public WMLS_UpdateInStoreRequest(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.XMLin = XMLin;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_UpdateInStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_UpdateInStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_UpdateInStoreResponse()
        {
        }
        
        public WMLS_UpdateInStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IWitsmlStoreChannel : WitsmlStoreServiceReference.IWitsmlStore, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WitsmlStoreClient : System.ServiceModel.ClientBase<WitsmlStoreServiceReference.IWitsmlStore>, WitsmlStoreServiceReference.IWitsmlStore
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WitsmlStoreClient() : 
                base(WitsmlStoreClient.GetDefaultBinding(), WitsmlStoreClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WitsmlStore.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WitsmlStoreClient(EndpointConfiguration endpointConfiguration) : 
                base(WitsmlStoreClient.GetBindingForEndpoint(endpointConfiguration), WitsmlStoreClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WitsmlStoreClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WitsmlStoreClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WitsmlStoreClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WitsmlStoreClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WitsmlStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_AddToStoreResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_AddToStore(WitsmlStoreServiceReference.WMLS_AddToStoreRequest request)
        {
            return base.Channel.WMLS_AddToStore(request);
        }
        
        public short WMLS_AddToStore(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            WitsmlStoreServiceReference.WMLS_AddToStoreRequest inValue = new WitsmlStoreServiceReference.WMLS_AddToStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.XMLin = XMLin;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            WitsmlStoreServiceReference.WMLS_AddToStoreResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_AddToStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_AddToStoreResponse> WMLS_AddToStoreAsync(WitsmlStoreServiceReference.WMLS_AddToStoreRequest request)
        {
            return base.Channel.WMLS_AddToStoreAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_DeleteFromStoreResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_DeleteFromStore(WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest request)
        {
            return base.Channel.WMLS_DeleteFromStore(request);
        }
        
        public short WMLS_DeleteFromStore(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest inValue = new WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.QueryIn = QueryIn;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            WitsmlStoreServiceReference.WMLS_DeleteFromStoreResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_DeleteFromStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_DeleteFromStoreResponse> WMLS_DeleteFromStoreAsync(WitsmlStoreServiceReference.WMLS_DeleteFromStoreRequest request)
        {
            return base.Channel.WMLS_DeleteFromStoreAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetBaseMsg(WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest request)
        {
            return base.Channel.WMLS_GetBaseMsg(request);
        }
        
        public string WMLS_GetBaseMsg(short ReturnValueIn)
        {
            WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest inValue = new WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest();
            inValue.ReturnValueIn = ReturnValueIn;
            WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetBaseMsg(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse> WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetBaseMsgAsync(WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest request)
        {
            return base.Channel.WMLS_GetBaseMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetBaseMsgResponse> WMLS_GetBaseMsgAsync(short ReturnValueIn)
        {
            WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest inValue = new WitsmlStoreServiceReference.WMLS_GetBaseMsgRequest();
            inValue.ReturnValueIn = ReturnValueIn;
            return ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetBaseMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_GetCapResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetCap(WitsmlStoreServiceReference.WMLS_GetCapRequest request)
        {
            return base.Channel.WMLS_GetCap(request);
        }
        
        public short WMLS_GetCap(string OptionsIn, out string CapabilitiesOut, out string SuppMsgOut)
        {
            WitsmlStoreServiceReference.WMLS_GetCapRequest inValue = new WitsmlStoreServiceReference.WMLS_GetCapRequest();
            inValue.OptionsIn = OptionsIn;
            WitsmlStoreServiceReference.WMLS_GetCapResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetCap(inValue);
            CapabilitiesOut = retVal.CapabilitiesOut;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetCapResponse> WMLS_GetCapAsync(WitsmlStoreServiceReference.WMLS_GetCapRequest request)
        {
            return base.Channel.WMLS_GetCapAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_GetFromStoreResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetFromStore(WitsmlStoreServiceReference.WMLS_GetFromStoreRequest request)
        {
            return base.Channel.WMLS_GetFromStore(request);
        }
        
        public short WMLS_GetFromStore(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn, out string XMLout, out string SuppMsgOut)
        {
            WitsmlStoreServiceReference.WMLS_GetFromStoreRequest inValue = new WitsmlStoreServiceReference.WMLS_GetFromStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.QueryIn = QueryIn;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            WitsmlStoreServiceReference.WMLS_GetFromStoreResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetFromStore(inValue);
            XMLout = retVal.XMLout;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetFromStoreResponse> WMLS_GetFromStoreAsync(WitsmlStoreServiceReference.WMLS_GetFromStoreRequest request)
        {
            return base.Channel.WMLS_GetFromStoreAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_GetVersionResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetVersion(WitsmlStoreServiceReference.WMLS_GetVersionRequest request)
        {
            return base.Channel.WMLS_GetVersion(request);
        }
        
        public string WMLS_GetVersion()
        {
            WitsmlStoreServiceReference.WMLS_GetVersionRequest inValue = new WitsmlStoreServiceReference.WMLS_GetVersionRequest();
            WitsmlStoreServiceReference.WMLS_GetVersionResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetVersion(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetVersionResponse> WitsmlStoreServiceReference.IWitsmlStore.WMLS_GetVersionAsync(WitsmlStoreServiceReference.WMLS_GetVersionRequest request)
        {
            return base.Channel.WMLS_GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_GetVersionResponse> WMLS_GetVersionAsync()
        {
            WitsmlStoreServiceReference.WMLS_GetVersionRequest inValue = new WitsmlStoreServiceReference.WMLS_GetVersionRequest();
            return ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WitsmlStoreServiceReference.WMLS_UpdateInStoreResponse WitsmlStoreServiceReference.IWitsmlStore.WMLS_UpdateInStore(WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest request)
        {
            return base.Channel.WMLS_UpdateInStore(request);
        }
        
        public short WMLS_UpdateInStore(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest inValue = new WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.XMLin = XMLin;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            WitsmlStoreServiceReference.WMLS_UpdateInStoreResponse retVal = ((WitsmlStoreServiceReference.IWitsmlStore)(this)).WMLS_UpdateInStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<WitsmlStoreServiceReference.WMLS_UpdateInStoreResponse> WMLS_UpdateInStoreAsync(WitsmlStoreServiceReference.WMLS_UpdateInStoreRequest request)
        {
            return base.Channel.WMLS_UpdateInStoreAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WitsmlStore))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WitsmlStore))
            {
                return new System.ServiceModel.EndpointAddress("https://witsserver.oxinpetro.com/WitsmlStore.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WitsmlStoreClient.GetBindingForEndpoint(EndpointConfiguration.WitsmlStore);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WitsmlStoreClient.GetEndpointAddress(EndpointConfiguration.WitsmlStore);
        }
        
        public enum EndpointConfiguration
        {
            
            WitsmlStore,
        }
    }
}
